language: python
sudo: required
python:
    - 2.7.8
    - 3.2
    - "pypy"

notifications:
  email: false

install:
  - pip install -r requirements.txt

script:
  python -m unittest discover ./knxReTk/test/
